name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: npm run start:prod

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      run: |
        # Add deployment steps here, e.g., deploying to a server, cloud platform, or container registry
        # You'll need to define your own deployment process

